### ISSUE TITLE
Add Karl Sööt's name to the name pool (new UX Designer starting Monday)

### ISSUE THREAD

**Issue by h4nna-h4x0r** [pixelfusion/match-magic#1]
Teach me how to do this! 💯

**Comment by yswery** [comment]
+1 as soon as he is on slack we will add him since we will need his Slack account ID first

**Comment by h4nna-h4x0r** [comment]
👌

**Comment by yswery** [comment]
Karl was added to the pool of people. 

And not only that, by chance he was also selected! 

_Cupid, you da real MVP_

**Comment by D4N-H4x0r** [comment]
And with the boss too!:clap:
