### ISSUE TITLE
"File selected" confirmation

### ISSUE THREAD

**Issue by jpcaparas** [pixelfusion/match-magic#11]
Hi guys,

Here's what the form looks looks like after I select a photo on my phone:

![unnamed__1_](https://user-images.githubusercontent.com/2406808/29189454-b1fd8058-7e6a-11e7-82b9-4a749cf86090.jpg)

_(I also checked on desktop and it has the same behaviour)_

As you can see above, there's currently +no indication+ of which file is being uploaded, as opposed to the standard `<input type="upload">` element behaviour that displays a label of the file selected. 

Would be awesome to bring this functionality back, or at the very least emulate it.

**Comment by h4nna-h4x0r** [comment]
Awesome, thanks JP! We're always looking for improvements 👍 :)

**Comment by D4N-H4x0r** [comment]
This is great! I think we can solve this along with the ux-redesign task :)

**Comment by jpcaparas** [comment]
😊

**Comment by shanemoses-pixelfusion** [comment]
https://github.com/pixelfusion/match-magic/pull/25 Merged to Master. Deployed to Production.
