### ISSUE TITLE
Add Luke.P to name pool 

### ISSUE THREAD

**Issue by h4nna-h4x0r** [pixelfusion/match-magic#15]
Teach me how to do this! @yswery @shanemoses-pixelfusion

**Comment by shanemoses-pixelfusion** [comment]
@h4nna-h4x0r what we actually need to work on is adding an admin section for you to take some control over the platform and users if need be (i.e. Adding, updating of users, temp disabling of users away on leave and maybe adding some extra details that we can add like Birthdays)

I'll be shifting my focus onto that admin platform real soon! and I'll create the stories for that, but for now its a complete manual process that either @yswery or I can do, sorry about that...

**Comment by h4nna-h4x0r** [comment]
Algood 👍  makes sense!

**Comment by yswery** [comment]
@h4nna-h4x0r has already done this (WOO BOSS WOMAN!)

closing this specific issue. will still need to add an admin of sorts
