### ISSUE TITLE
Add Wison / Maryam / Anthony to Match Magic list 

### ISSUE THREAD

**Issue by h4nna-h4x0r** [pixelfusion/match-magic#18]
I think I can do this.......... I will try and remember how I did it last time :P

**Comment by yswery** [comment]
Let me know when you want this done I can slack you the SLACK IDs and we can do this together (shoud not take longer than 10mins to add them in)

**Comment by h4nna-h4x0r** [comment]
sweet :D

**Comment by shanemoses-pixelfusion** [comment]
This is done. @h4nna-h4x0r @yswery GREAT STUFF!!! 👍
